# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from op3_tuning_module_msgs/JointTorqueOnOffArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import op3_tuning_module_msgs.msg

class JointTorqueOnOffArray(genpy.Message):
  _md5sum = "1ca4db772b4d802ac00aebf4469fc8bf"
  _type = "op3_tuning_module_msgs/JointTorqueOnOffArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """JointTorqueOnOff[] torque_enable_data
================================================================================
MSG: op3_tuning_module_msgs/JointTorqueOnOff
string  joint_name
bool    torque_enable"""
  __slots__ = ['torque_enable_data']
  _slot_types = ['op3_tuning_module_msgs/JointTorqueOnOff[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       torque_enable_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointTorqueOnOffArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.torque_enable_data is None:
        self.torque_enable_data = []
    else:
      self.torque_enable_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.torque_enable_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.torque_enable_data:
        _x = val1.joint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.torque_enable
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.torque_enable_data is None:
        self.torque_enable_data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.torque_enable_data = []
      for i in range(0, length):
        val1 = op3_tuning_module_msgs.msg.JointTorqueOnOff()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.joint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.joint_name = str[start:end]
        start = end
        end += 1
        (val1.torque_enable,) = _get_struct_B().unpack(str[start:end])
        val1.torque_enable = bool(val1.torque_enable)
        self.torque_enable_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.torque_enable_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.torque_enable_data:
        _x = val1.joint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.torque_enable
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.torque_enable_data is None:
        self.torque_enable_data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.torque_enable_data = []
      for i in range(0, length):
        val1 = op3_tuning_module_msgs.msg.JointTorqueOnOff()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.joint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.joint_name = str[start:end]
        start = end
        end += 1
        (val1.torque_enable,) = _get_struct_B().unpack(str[start:end])
        val1.torque_enable = bool(val1.torque_enable)
        self.torque_enable_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
