// Generated by gencpp from file op3_action_module_msgs/IsRunning.msg
// DO NOT EDIT!


#ifndef OP3_ACTION_MODULE_MSGS_MESSAGE_ISRUNNING_H
#define OP3_ACTION_MODULE_MSGS_MESSAGE_ISRUNNING_H

#include <ros/service_traits.h>


#include <op3_action_module_msgs/IsRunningRequest.h>
#include <op3_action_module_msgs/IsRunningResponse.h>


namespace op3_action_module_msgs
{

struct IsRunning
{

typedef IsRunningRequest Request;
typedef IsRunningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsRunning
} // namespace op3_action_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_action_module_msgs::IsRunning > {
  static const char* value()
  {
    return "ae3468a1af93d845e943210e7cef5a54";
  }

  static const char* value(const ::op3_action_module_msgs::IsRunning&) { return value(); }
};

template<>
struct DataType< ::op3_action_module_msgs::IsRunning > {
  static const char* value()
  {
    return "op3_action_module_msgs/IsRunning";
  }

  static const char* value(const ::op3_action_module_msgs::IsRunning&) { return value(); }
};


// service_traits::MD5Sum< ::op3_action_module_msgs::IsRunningRequest> should match 
// service_traits::MD5Sum< ::op3_action_module_msgs::IsRunning > 
template<>
struct MD5Sum< ::op3_action_module_msgs::IsRunningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_action_module_msgs::IsRunning >::value();
  }
  static const char* value(const ::op3_action_module_msgs::IsRunningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_action_module_msgs::IsRunningRequest> should match 
// service_traits::DataType< ::op3_action_module_msgs::IsRunning > 
template<>
struct DataType< ::op3_action_module_msgs::IsRunningRequest>
{
  static const char* value()
  {
    return DataType< ::op3_action_module_msgs::IsRunning >::value();
  }
  static const char* value(const ::op3_action_module_msgs::IsRunningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_action_module_msgs::IsRunningResponse> should match 
// service_traits::MD5Sum< ::op3_action_module_msgs::IsRunning > 
template<>
struct MD5Sum< ::op3_action_module_msgs::IsRunningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_action_module_msgs::IsRunning >::value();
  }
  static const char* value(const ::op3_action_module_msgs::IsRunningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_action_module_msgs::IsRunningResponse> should match 
// service_traits::DataType< ::op3_action_module_msgs::IsRunning > 
template<>
struct DataType< ::op3_action_module_msgs::IsRunningResponse>
{
  static const char* value()
  {
    return DataType< ::op3_action_module_msgs::IsRunning >::value();
  }
  static const char* value(const ::op3_action_module_msgs::IsRunningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_ACTION_MODULE_MSGS_MESSAGE_ISRUNNING_H
