(cl:defpackage op3_online_walking_module_msgs-srv
  (:use )
  (:export
   "GETJOINTPOSE"
   "<GETJOINTPOSE-REQUEST>"
   "GETJOINTPOSE-REQUEST"
   "<GETJOINTPOSE-RESPONSE>"
   "GETJOINTPOSE-RESPONSE"
   "GETKINEMATICSPOSE"
   "<GETKINEMATICSPOSE-REQUEST>"
   "GETKINEMATICSPOSE-REQUEST"
   "<GETKINEMATICSPOSE-RESPONSE>"
   "GETKINEMATICSPOSE-RESPONSE"
   "GETPREVIEWMATRIX"
   "<GETPREVIEWMATRIX-REQUEST>"
   "GETPREVIEWMATRIX-REQUEST"
   "<GETPREVIEWMATRIX-RESPONSE>"
   "GETPREVIEWMATRIX-RESPONSE"
  ))

