// Generated by gencpp from file op3_ball_detector/GetParameters.msg
// DO NOT EDIT!


#ifndef OP3_BALL_DETECTOR_MESSAGE_GETPARAMETERS_H
#define OP3_BALL_DETECTOR_MESSAGE_GETPARAMETERS_H

#include <ros/service_traits.h>


#include <op3_ball_detector/GetParametersRequest.h>
#include <op3_ball_detector/GetParametersResponse.h>


namespace op3_ball_detector
{

struct GetParameters
{

typedef GetParametersRequest Request;
typedef GetParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParameters
} // namespace op3_ball_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_ball_detector::GetParameters > {
  static const char* value()
  {
    return "17229f06a68a0d87fd525e4d8bdaee90";
  }

  static const char* value(const ::op3_ball_detector::GetParameters&) { return value(); }
};

template<>
struct DataType< ::op3_ball_detector::GetParameters > {
  static const char* value()
  {
    return "op3_ball_detector/GetParameters";
  }

  static const char* value(const ::op3_ball_detector::GetParameters&) { return value(); }
};


// service_traits::MD5Sum< ::op3_ball_detector::GetParametersRequest> should match 
// service_traits::MD5Sum< ::op3_ball_detector::GetParameters > 
template<>
struct MD5Sum< ::op3_ball_detector::GetParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_ball_detector::GetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::GetParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_ball_detector::GetParametersRequest> should match 
// service_traits::DataType< ::op3_ball_detector::GetParameters > 
template<>
struct DataType< ::op3_ball_detector::GetParametersRequest>
{
  static const char* value()
  {
    return DataType< ::op3_ball_detector::GetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::GetParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_ball_detector::GetParametersResponse> should match 
// service_traits::MD5Sum< ::op3_ball_detector::GetParameters > 
template<>
struct MD5Sum< ::op3_ball_detector::GetParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_ball_detector::GetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::GetParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_ball_detector::GetParametersResponse> should match 
// service_traits::DataType< ::op3_ball_detector::GetParameters > 
template<>
struct DataType< ::op3_ball_detector::GetParametersResponse>
{
  static const char* value()
  {
    return DataType< ::op3_ball_detector::GetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::GetParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_BALL_DETECTOR_MESSAGE_GETPARAMETERS_H
