// Generated by gencpp from file op3_ball_detector/SetParameters.msg
// DO NOT EDIT!


#ifndef OP3_BALL_DETECTOR_MESSAGE_SETPARAMETERS_H
#define OP3_BALL_DETECTOR_MESSAGE_SETPARAMETERS_H

#include <ros/service_traits.h>


#include <op3_ball_detector/SetParametersRequest.h>
#include <op3_ball_detector/SetParametersResponse.h>


namespace op3_ball_detector
{

struct SetParameters
{

typedef SetParametersRequest Request;
typedef SetParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameters
} // namespace op3_ball_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_ball_detector::SetParameters > {
  static const char* value()
  {
    return "b144be2bfcda348236c05dcc43378583";
  }

  static const char* value(const ::op3_ball_detector::SetParameters&) { return value(); }
};

template<>
struct DataType< ::op3_ball_detector::SetParameters > {
  static const char* value()
  {
    return "op3_ball_detector/SetParameters";
  }

  static const char* value(const ::op3_ball_detector::SetParameters&) { return value(); }
};


// service_traits::MD5Sum< ::op3_ball_detector::SetParametersRequest> should match 
// service_traits::MD5Sum< ::op3_ball_detector::SetParameters > 
template<>
struct MD5Sum< ::op3_ball_detector::SetParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_ball_detector::SetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_ball_detector::SetParametersRequest> should match 
// service_traits::DataType< ::op3_ball_detector::SetParameters > 
template<>
struct DataType< ::op3_ball_detector::SetParametersRequest>
{
  static const char* value()
  {
    return DataType< ::op3_ball_detector::SetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_ball_detector::SetParametersResponse> should match 
// service_traits::MD5Sum< ::op3_ball_detector::SetParameters > 
template<>
struct MD5Sum< ::op3_ball_detector::SetParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_ball_detector::SetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::SetParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_ball_detector::SetParametersResponse> should match 
// service_traits::DataType< ::op3_ball_detector::SetParameters > 
template<>
struct DataType< ::op3_ball_detector::SetParametersResponse>
{
  static const char* value()
  {
    return DataType< ::op3_ball_detector::SetParameters >::value();
  }
  static const char* value(const ::op3_ball_detector::SetParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_BALL_DETECTOR_MESSAGE_SETPARAMETERS_H
