// Generated by gencpp from file op3_tuning_module_msgs/GetPresentJointOffsetData.msg
// DO NOT EDIT!


#ifndef OP3_TUNING_MODULE_MSGS_MESSAGE_GETPRESENTJOINTOFFSETDATA_H
#define OP3_TUNING_MODULE_MSGS_MESSAGE_GETPRESENTJOINTOFFSETDATA_H

#include <ros/service_traits.h>


#include <op3_tuning_module_msgs/GetPresentJointOffsetDataRequest.h>
#include <op3_tuning_module_msgs/GetPresentJointOffsetDataResponse.h>


namespace op3_tuning_module_msgs
{

struct GetPresentJointOffsetData
{

typedef GetPresentJointOffsetDataRequest Request;
typedef GetPresentJointOffsetDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPresentJointOffsetData
} // namespace op3_tuning_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetData > {
  static const char* value()
  {
    return "fe3cab7abbd49468a5d502064853404e";
  }

  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetData&) { return value(); }
};

template<>
struct DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetData > {
  static const char* value()
  {
    return "op3_tuning_module_msgs/GetPresentJointOffsetData";
  }

  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetData&) { return value(); }
};


// service_traits::MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest> should match 
// service_traits::MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetData > 
template<>
struct MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetData >::value();
  }
  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest> should match 
// service_traits::DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetData > 
template<>
struct DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest>
{
  static const char* value()
  {
    return DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetData >::value();
  }
  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse> should match 
// service_traits::MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetData > 
template<>
struct MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_tuning_module_msgs::GetPresentJointOffsetData >::value();
  }
  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse> should match 
// service_traits::DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetData > 
template<>
struct DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse>
{
  static const char* value()
  {
    return DataType< ::op3_tuning_module_msgs::GetPresentJointOffsetData >::value();
  }
  static const char* value(const ::op3_tuning_module_msgs::GetPresentJointOffsetDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_TUNING_MODULE_MSGS_MESSAGE_GETPRESENTJOINTOFFSETDATA_H
