(cl:defpackage op3_online_walking_module_msgs-msg
  (:use )
  (:export
   "<FOOTSTEPARRAY>"
   "FOOTSTEPARRAY"
   "<FOOTSTEPCOMMAND>"
   "FOOTSTEPCOMMAND"
   "<JOINTPOSE>"
   "JOINTPOSE"
   "<KINEMATICSPOSE>"
   "KINEMATICSPOSE"
   "<PREVIEWREQUEST>"
   "PREVIEWREQUEST"
   "<PREVIEWRESPONSE>"
   "PREVIEWRESPONSE"
   "<STEP2D>"
   "STEP2D"
   "<STEP2DARRAY>"
   "STEP2DARRAY"
   "<WALKINGPARAM>"
   "WALKINGPARAM"
  ))

