(cl:defpackage op3_camera_setting_tool-srv
  (:use )
  (:export
   "GETPARAMETERS"
   "<GETPARAMETERS-REQUEST>"
   "GETPARAMETERS-REQUEST"
   "<GETPARAMETERS-RESPONSE>"
   "GETPARAMETERS-RESPONSE"
   "SETPARAMETERS"
   "<SETPARAMETERS-REQUEST>"
   "SETPARAMETERS-REQUEST"
   "<SETPARAMETERS-RESPONSE>"
   "SETPARAMETERS-RESPONSE"
  ))

