(cl:in-package op3_ball_detector-msg)
(cl:export '(GAUSSIAN_BLUR_SIZE-VAL
          GAUSSIAN_BLUR_SIZE
          GAUSSIAN_BLUR_SIGMA-VAL
          GAUSSIAN_BLUR_SIGMA
          CANNY_EDGE_TH-VAL
          CANNY_EDGE_TH
          HOUGH_ACCUM_RESOLUTION-VAL
          HOUGH_ACCUM_RESOLUTION
          HOUGH_ACCUM_TH-VAL
          HOUGH_ACCUM_TH
          MIN_CIRCLE_DIST-VAL
          MIN_CIRCLE_DIST
          MIN_RADIUS-VAL
          MIN_RADIUS
          MAX_RADIUS-VAL
          MAX_RADIUS
          FILTER_H_MIN-VAL
          FILTER_H_MIN
          FILTER_H_MAX-VAL
          FILTER_H_MAX
          FILTER_S_MIN-VAL
          FILTER_S_MIN
          FILTER_S_MAX-VAL
          FILTER_S_MAX
          FILTER_V_MIN-VAL
          FILTER_V_MIN
          FILTER_V_MAX-VAL
          FILTER_V_MAX
          ELLIPSE_SIZE-VAL
          ELLIPSE_SIZE
))