// Generated by gencpp from file imu_odom_and_twist_msgs/ImuOdomAndTwist.msg
// DO NOT EDIT!


#ifndef IMU_ODOM_AND_TWIST_MSGS_MESSAGE_IMUODOMANDTWIST_H
#define IMU_ODOM_AND_TWIST_MSGS_MESSAGE_IMUODOMANDTWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>
#include <geometry_msgs/TwistStamped.h>

namespace imu_odom_and_twist_msgs
{
template <class ContainerAllocator>
struct ImuOdomAndTwist_
{
  typedef ImuOdomAndTwist_<ContainerAllocator> Type;

  ImuOdomAndTwist_()
    : header()
    , imu_odom()
    , cmd_vel()  {
    }
  ImuOdomAndTwist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , imu_odom(_alloc)
    , cmd_vel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _imu_odom_type;
  _imu_odom_type imu_odom;

   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _cmd_vel_type;
  _cmd_vel_type cmd_vel;





  typedef boost::shared_ptr< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> const> ConstPtr;

}; // struct ImuOdomAndTwist_

typedef ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<std::allocator<void> > ImuOdomAndTwist;

typedef boost::shared_ptr< ::imu_odom_and_twist_msgs::ImuOdomAndTwist > ImuOdomAndTwistPtr;
typedef boost::shared_ptr< ::imu_odom_and_twist_msgs::ImuOdomAndTwist const> ImuOdomAndTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_odom_and_twist_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'imu_odom_and_twist_msgs': ['/home/benjamin/ROCO318/catkin_ws/src/imu_odom_and_twist_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8822385b6f08ae05ac9da58f2dd82b25";
  }

  static const char* value(const ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8822385b6f08ae05ULL;
  static const uint64_t static_value2 = 0xac9da58f2dd82b25ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_odom_and_twist_msgs/ImuOdomAndTwist";
  }

  static const char* value(const ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
nav_msgs/Odometry imu_odom\n\
geometry_msgs/TwistStamped cmd_vel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
";
  }

  static const char* value(const ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.imu_odom);
      stream.next(m.cmd_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuOdomAndTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_odom_and_twist_msgs::ImuOdomAndTwist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "imu_odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.imu_odom);
    s << indent << "cmd_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_ODOM_AND_TWIST_MSGS_MESSAGE_IMUODOMANDTWIST_H
