// Generated by gencpp from file op3_online_walking_module_msgs/FootStepArray.msg
// DO NOT EDIT!


#ifndef OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_FOOTSTEPARRAY_H
#define OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_FOOTSTEPARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace op3_online_walking_module_msgs
{
template <class ContainerAllocator>
struct FootStepArray_
{
  typedef FootStepArray_<ContainerAllocator> Type;

  FootStepArray_()
    : moving_foot()
    , data()  {
    }
  FootStepArray_(const ContainerAllocator& _alloc)
    : moving_foot(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _moving_foot_type;
  _moving_foot_type moving_foot;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _data_type;
  _data_type data;



  enum {
    LEFT_FOOT = 0,
    RIGHT_FOOT = 1,
  };


  typedef boost::shared_ptr< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> const> ConstPtr;

}; // struct FootStepArray_

typedef ::op3_online_walking_module_msgs::FootStepArray_<std::allocator<void> > FootStepArray;

typedef boost::shared_ptr< ::op3_online_walking_module_msgs::FootStepArray > FootStepArrayPtr;
typedef boost::shared_ptr< ::op3_online_walking_module_msgs::FootStepArray const> FootStepArrayConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace op3_online_walking_module_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'op3_online_walking_module_msgs': ['/home/benjamin/ROCO318/catkin_ws/src/ROBOTIS-OP3-msgs/op3_online_walking_module_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d024e75ed0a26f72c71cd63c2720fb63";
  }

  static const char* value(const ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd024e75ed0a26f72ULL;
  static const uint64_t static_value2 = 0xc71cd63c2720fb63ULL;
};

template<class ContainerAllocator>
struct DataType< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "op3_online_walking_module_msgs/FootStepArray";
  }

  static const char* value(const ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 LEFT_FOOT  = 0 # Left foot constant\n\
int32 RIGHT_FOOT = 1 # Right foot constant\n\
\n\
int32[]                moving_foot\n\
geometry_msgs/Pose2D[] data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.moving_foot);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FootStepArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::op3_online_walking_module_msgs::FootStepArray_<ContainerAllocator>& v)
  {
    s << indent << "moving_foot[]" << std::endl;
    for (size_t i = 0; i < v.moving_foot.size(); ++i)
    {
      s << indent << "  moving_foot[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.moving_foot[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_FOOTSTEPARRAY_H
