// Generated by gencpp from file op3_online_walking_module_msgs/GetJointPose.msg
// DO NOT EDIT!


#ifndef OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H
#define OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H

#include <ros/service_traits.h>


#include <op3_online_walking_module_msgs/GetJointPoseRequest.h>
#include <op3_online_walking_module_msgs/GetJointPoseResponse.h>


namespace op3_online_walking_module_msgs
{

struct GetJointPose
{

typedef GetJointPoseRequest Request;
typedef GetJointPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointPose
} // namespace op3_online_walking_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetJointPose > {
  static const char* value()
  {
    return "c1260c47b7c0dc9a41639ef7730118eb";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetJointPose&) { return value(); }
};

template<>
struct DataType< ::op3_online_walking_module_msgs::GetJointPose > {
  static const char* value()
  {
    return "op3_online_walking_module_msgs/GetJointPose";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetJointPose&) { return value(); }
};


// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetJointPoseRequest> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetJointPose > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetJointPoseRequest> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetJointPose > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetJointPoseResponse> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetJointPose > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetJointPoseResponse> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetJointPose > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H
