// Generated by gencpp from file op3_online_walking_module_msgs/GetKinematicsPose.msg
// DO NOT EDIT!


#ifndef OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSE_H
#define OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSE_H

#include <ros/service_traits.h>


#include <op3_online_walking_module_msgs/GetKinematicsPoseRequest.h>
#include <op3_online_walking_module_msgs/GetKinematicsPoseResponse.h>


namespace op3_online_walking_module_msgs
{

struct GetKinematicsPose
{

typedef GetKinematicsPoseRequest Request;
typedef GetKinematicsPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetKinematicsPose
} // namespace op3_online_walking_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPose > {
  static const char* value()
  {
    return "aad71eecbad83fbcb051be59f9fbb914";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPose&) { return value(); }
};

template<>
struct DataType< ::op3_online_walking_module_msgs::GetKinematicsPose > {
  static const char* value()
  {
    return "op3_online_walking_module_msgs/GetKinematicsPose";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPose&) { return value(); }
};


// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPoseRequest> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPose > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetKinematicsPoseRequest> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetKinematicsPose > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetKinematicsPoseRequest>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPoseResponse> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPose > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetKinematicsPoseResponse> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetKinematicsPose > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetKinematicsPoseResponse>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetKinematicsPose >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetKinematicsPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSE_H
