// Generated by gencpp from file op3_online_walking_module_msgs/GetPreviewMatrix.msg
// DO NOT EDIT!


#ifndef OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETPREVIEWMATRIX_H
#define OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETPREVIEWMATRIX_H

#include <ros/service_traits.h>


#include <op3_online_walking_module_msgs/GetPreviewMatrixRequest.h>
#include <op3_online_walking_module_msgs/GetPreviewMatrixResponse.h>


namespace op3_online_walking_module_msgs
{

struct GetPreviewMatrix
{

typedef GetPreviewMatrixRequest Request;
typedef GetPreviewMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPreviewMatrix
} // namespace op3_online_walking_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrix > {
  static const char* value()
  {
    return "353f820108e54e41d7780433bc38ff53";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrix&) { return value(); }
};

template<>
struct DataType< ::op3_online_walking_module_msgs::GetPreviewMatrix > {
  static const char* value()
  {
    return "op3_online_walking_module_msgs/GetPreviewMatrix";
  }

  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrixRequest> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrix > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrix >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetPreviewMatrixRequest> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetPreviewMatrix > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetPreviewMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetPreviewMatrix >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrixResponse> should match 
// service_traits::MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrix > 
template<>
struct MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_online_walking_module_msgs::GetPreviewMatrix >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_online_walking_module_msgs::GetPreviewMatrixResponse> should match 
// service_traits::DataType< ::op3_online_walking_module_msgs::GetPreviewMatrix > 
template<>
struct DataType< ::op3_online_walking_module_msgs::GetPreviewMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::op3_online_walking_module_msgs::GetPreviewMatrix >::value();
  }
  static const char* value(const ::op3_online_walking_module_msgs::GetPreviewMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_ONLINE_WALKING_MODULE_MSGS_MESSAGE_GETPREVIEWMATRIX_H
