// Generated by gencpp from file op3_camera_setting_tool/SetParameters.msg
// DO NOT EDIT!


#ifndef OP3_CAMERA_SETTING_TOOL_MESSAGE_SETPARAMETERS_H
#define OP3_CAMERA_SETTING_TOOL_MESSAGE_SETPARAMETERS_H

#include <ros/service_traits.h>


#include <op3_camera_setting_tool/SetParametersRequest.h>
#include <op3_camera_setting_tool/SetParametersResponse.h>


namespace op3_camera_setting_tool
{

struct SetParameters
{

typedef SetParametersRequest Request;
typedef SetParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameters
} // namespace op3_camera_setting_tool


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::op3_camera_setting_tool::SetParameters > {
  static const char* value()
  {
    return "f3fa160e05eef0ff6c5a3f1ecaa69cbc";
  }

  static const char* value(const ::op3_camera_setting_tool::SetParameters&) { return value(); }
};

template<>
struct DataType< ::op3_camera_setting_tool::SetParameters > {
  static const char* value()
  {
    return "op3_camera_setting_tool/SetParameters";
  }

  static const char* value(const ::op3_camera_setting_tool::SetParameters&) { return value(); }
};


// service_traits::MD5Sum< ::op3_camera_setting_tool::SetParametersRequest> should match 
// service_traits::MD5Sum< ::op3_camera_setting_tool::SetParameters > 
template<>
struct MD5Sum< ::op3_camera_setting_tool::SetParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::op3_camera_setting_tool::SetParameters >::value();
  }
  static const char* value(const ::op3_camera_setting_tool::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_camera_setting_tool::SetParametersRequest> should match 
// service_traits::DataType< ::op3_camera_setting_tool::SetParameters > 
template<>
struct DataType< ::op3_camera_setting_tool::SetParametersRequest>
{
  static const char* value()
  {
    return DataType< ::op3_camera_setting_tool::SetParameters >::value();
  }
  static const char* value(const ::op3_camera_setting_tool::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::op3_camera_setting_tool::SetParametersResponse> should match 
// service_traits::MD5Sum< ::op3_camera_setting_tool::SetParameters > 
template<>
struct MD5Sum< ::op3_camera_setting_tool::SetParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::op3_camera_setting_tool::SetParameters >::value();
  }
  static const char* value(const ::op3_camera_setting_tool::SetParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::op3_camera_setting_tool::SetParametersResponse> should match 
// service_traits::DataType< ::op3_camera_setting_tool::SetParameters > 
template<>
struct DataType< ::op3_camera_setting_tool::SetParametersResponse>
{
  static const char* value()
  {
    return DataType< ::op3_camera_setting_tool::SetParameters >::value();
  }
  static const char* value(const ::op3_camera_setting_tool::SetParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OP3_CAMERA_SETTING_TOOL_MESSAGE_SETPARAMETERS_H
