(cl:defpackage op3_walking_module_msgs-srv
  (:use )
  (:export
   "GETWALKINGPARAM"
   "<GETWALKINGPARAM-REQUEST>"
   "GETWALKINGPARAM-REQUEST"
   "<GETWALKINGPARAM-RESPONSE>"
   "GETWALKINGPARAM-RESPONSE"
   "SETWALKINGPARAM"
   "<SETWALKINGPARAM-REQUEST>"
   "SETWALKINGPARAM-REQUEST"
   "<SETWALKINGPARAM-RESPONSE>"
   "SETWALKINGPARAM-RESPONSE"
  ))

